import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideDrawer from '@/components/Sidebar'
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "new layout",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body className={inter.className}>
            <div className="flex h-screen overflow-hidden">
                <div className={`fixed top-0 bottom-0 z-30 transform md:translate-x-0 transition-transform duration-300 ease-in-out md:w-64`}>
                    <SideDrawer />
                </div>
                <div className="fixed inset-0 -z-10 h-full w-full bg-white bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#e0e0e0_1px,transparent_1px)] bg-[size:6rem_4rem]"><div className="absolute bottom-0 left-0 right-0 top-0 bg-[radial-gradient(circle_800px_at_100%_200px,transparent)]"></div></div>

                <div className="flex-1 md:ml-64 overflow-y-auto">
                    {children}
                </div>
            </div>
        </body>
        </html>
    );
}
