import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideDrawer from '@/components/Sidebar'
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "new layout",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <div className="flex">
                <div className="md:w-64">
                    <SideDrawer />
                </div>
                {children}
            </div>
        </body>
        </html>
    );
}
